version: "3.2"
services:
  backend:
    hostname: api
    container_name: backend
    build: ./backend
    environment:
      - GIN_MODE=debug
      - SUPABASE_URL=$SUPABASE_URL
      - SUPABASE_API_KEY=$SUPABASE_API_KEY
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
    networks:
      - proxy

  frontend:
    hostname: app
    container_name: kakeibo
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    environment:
      - REACT_APP_FILEBASE_ACCESS_ID=$FILEBASE_ACCESS_KEY_ID
      - REACT_APP_FILEBASE_SECRET_ACCESS_KEY=$FILEBASE_SECRET_ACCESS_KEY
      - REACT_APP_SUPABASE_API_KEY=${SUPABASE_API_KEY}
    depends_on:
      - backend
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  cache:
    driver: local

