FROM node:16-alpine as build

WORKDIR /usr/src/app

COPY package.json ./
COPY yarn.lock ./
RUN apk --no-cache add git
RUN yarn install

COPY . .

CMD ["yarn", "build"]

FROM nginx:alpine as serve

COPY ./docker/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /usr/src/app/build /usr/share/nginx/html

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]

